### ISSUE TITLE
Variables defined in previous episode

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/python-novice-inflammation-colab#13]
> Hi James,
\
I'm having issue with this:
\
https://swcarpentry.github.io/python-novice-inflammation/03-matplotlib/index.html
\
The first code chunk is:
\
import matplotlib.pyplot
image = matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show()
\
But data was not defined anywhere in the lesson. So I got this error:
\
\---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-577ea3d3f08b> in <module>()
----> 1 image = matplotlib.pyplot.imshow(data)
      2 matplotlib.pyplot.show()
\
NameError: name 'data' is not defined
\
\
I don't know if I understand the issue correctly, but how do I fix this?

cc @tientong98

**Comment by jdkent** [comment]
This is because `data` is defined in [`02-analyzing-patient-data`](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html#loading-data-into-python),
specifically:

```
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')
```

so for 03-matplotlib, the above line needs to be copied into the episode.

This may occur for other episodes as well, so keep a lookout!

**Comment by tien-tong** [comment]
Thanks @jdkent! 

In addition to variables being defined in the previous lessons, sometime the current lesson assumes you have already imported certain packages from previous lessons, so you might want to keep an eye out for that.
