### ISSUE TITLE
Next Year

### ISSUE THREAD

**Issue by mpipoly** [brainhack-uiowa/python-novice-inflammation-colab#14]
-Make sure to send flyer with a link "yes, no, maybe" for attendance and interest in Brainhack related events. This can be done in qualtrics?

**Comment by jdkent** [comment]
Good idea, yes, this can be done in qualtrics.

**Comment by mpipoly** [comment]
Just checking, this is closed because we discussed that it was late to do this now correct?

**Comment by jdkent** [comment]
I meant to copy this issue to https://github.com/brainhack-uiowa/2020-brainhack, since that is the repo we are tracking issues related to the general organization of the brainhack, whereas this one is about the google collab lessons, could you open the issue over there?
